# flower_data.py
# FIRST SECTION: Flowers 1-8
# Copy and paste this entire block into flower_data.py
# (It starts the list exactly as your GitHub repo expects)

flowers = [
    {
        "common_name": "French Marigold",
        "scientific_name": "Tagetes patula",
        "cultivar": "Tangerine Gem",
        "type": "Heirloom",
        "growth_habit": "Bushy (compact 8-12 inches)",
        "method": "Direct sow or starter",
        "depth": "1/4 inch",
        "spacing_traditional": "8-12 inches",
        "spacing_grid": "4 per sq. ft.",
        "care": "Full sun; deadhead for continuous bloom; drought tolerant once established.",
        "days_to_harvest": "45-60 days to bloom",
        "harvest_indicators": "Fully open bright orange flowers; cut stems when petals are vibrant.",
        "yield_family_2": "6-8 plants (for cutting + companion)",
        "yield_family_4": "12-16 plants",
        "preservation": "Fresh cut flowers or dry for potpourri and tea.",
        "granny_fanny": "These keep the bad bugs away from your tomatoes better than any spray ever could — plant them everywhere!",
        "companions": ["Tomatoes", "Peppers", "Beans", "Cucumbers"],
        "no_go": []
    },
    {
        "common_name": "Nasturtium",
        "scientific_name": "Tropaeolum majus",
        "cultivar": "Alaska Mix",
        "type": "Heirloom",
        "growth_habit": "Trailing/Vining (12-18 inches)",
        "method": "Direct sow after frost",
        "depth": "1/2 inch",
        "spacing_traditional": "12 inches",
        "spacing_grid": "2-3 per sq. ft.",
        "care": "Poor soil is fine; full sun to part shade; edible flowers and leaves.",
        "days_to_harvest": "50-60 days to bloom",
        "harvest_indicators": "Bright orange, red, or yellow flowers fully open; leaves vibrant green.",
        "yield_family_2": "4-6 plants",
        "yield_family_4": "8-12 plants",
        "preservation": "Fresh edible flowers/leaves or dry for tea and garnishes.",
        "granny_fanny": "Pretty AND edible — the peppery leaves and flowers make the best homestead pesto and salads!",
        "companions": ["Cucumbers", "Squash", "Beans", "Radishes"],
        "no_go": []
    },
    {
        "common_name": "Zinnia",
        "scientific_name": "Zinnia elegans",
        "cultivar": "State Fair Mix",
        "type": "Heirloom",
        "growth_habit": "Bushy (24-36 inches)",
        "method": "Direct sow or starter",
        "depth": "1/4 inch",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "2-3 per sq. ft.",
        "care": "Full sun; deadhead regularly; excellent cut-and-come-again.",
        "days_to_harvest": "50-60 days to bloom",
        "harvest_indicators": "Fully open daisy-like flowers in bright colors; sturdy stems.",
        "yield_family_2": "6-8 plants (for cutting)",
        "yield_family_4": "12-16 plants",
        "preservation": "Fresh cut flowers; dry for everlasting arrangements.",
        "granny_fanny": "These old-fashioned American beauties keep blooming till frost — perfect for filling vases all summer!",
        "companions": ["Tomatoes", "Peppers", "Basil"],
        "no_go": []
    },
    {
        "common_name": "Mammoth Sunflower",
        "scientific_name": "Helianthus annuus",
        "cultivar": "Mammoth Russian",
        "type": "Heirloom",
        "growth_habit": "Tall upright (6-12 ft)",
        "method": "Direct sow after frost",
        "depth": "1 inch",
        "spacing_traditional": "24-36 inches",
        "spacing_grid": "1 per 4 sq. ft.",
        "care": "Full sun; deep watering; stake tall varieties; bird-friendly.",
        "days_to_harvest": "70-90 days to bloom",
        "harvest_indicators": "Huge yellow heads with dark centers; petals drop when seeds mature.",
        "yield_family_2": "2-3 plants",
        "yield_family_4": "4-6 plants",
        "preservation": "Fresh cut flowers or harvest seeds for eating/roasting.",
        "granny_fanny": "One of these giants will feed the whole family with seeds AND give you the tallest fence in the neighborhood!",
        "companions": ["Corn", "Beans", "Squash"],
        "no_go": []
    },
    {
        "common_name": "Cosmos",
        "scientific_name": "Cosmos bipinnatus",
        "cultivar": "Sensation Mix",
        "type": "Heirloom",
        "growth_habit": "Tall airy (36-48 inches)",
        "method": "Direct sow after frost",
        "depth": "1/4 inch",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "2 per sq. ft.",
        "care": "Full sun; drought tolerant; self-seeding; deadhead for more blooms.",
        "days_to_harvest": "60-75 days to bloom",
        "harvest_indicators": "Daisy-like flowers in pinks, whites, and purples; feathery foliage.",
        "yield_family_2": "6-8 plants",
        "yield_family_4": "12-16 plants",
        "preservation": "Fresh cut flowers; excellent for bouquets.",
        "granny_fanny": "These Mexican natives bloom like crazy and bring butterflies and bees by the dozen!",
        "companions": ["Tomatoes", "Cucumbers", "Beans"],
        "no_go": []
    },
    {
        "common_name": "Calendula",
        "scientific_name": "Calendula officinalis",
        "cultivar": "Pacific Beauty",
        "type": "Heirloom",
        "growth_habit": "Bushy (12-24 inches)",
        "method": "Direct sow",
        "depth": "1/2 inch",
        "spacing_traditional": "12 inches",
        "spacing_grid": "3 per sq. ft.",
        "care": "Full sun to part shade; cool weather tolerant; deadhead for continuous bloom.",
        "days_to_harvest": "45-60 days to bloom",
        "harvest_indicators": "Bright orange/yellow daisy flowers; petals fully open.",
        "yield_family_2": "6 plants",
        "yield_family_4": "12 plants",
        "preservation": "Fresh or dry petals for tea, salves, and edibles.",
        "granny_fanny": "The old-timey 'pot marigold' — grow it for skin salves and pretty edible petals in your salads!",
        "companions": ["Tomatoes", "Peppers", "Asparagus"],
        "no_go": []
    },
    {
        "common_name": "Echinacea (Purple Coneflower)",
        "scientific_name": "Echinacea purpurea",
        "cultivar": "Magnus",
        "type": "Heirloom",
        "growth_habit": "Upright perennial (24-36 inches)",
        "method": "Starter recommended or direct sow",
        "depth": "1/4 inch",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1-2 per sq. ft.",
        "care": "Full sun; drought tolerant once established; leave seed heads for birds.",
        "days_to_harvest": "60-80 days to bloom (year 1)",
        "harvest_indicators": "Large purple daisy-like flowers with raised cone center.",
        "yield_family_2": "4-6 plants",
        "yield_family_4": "8-12 plants",
        "preservation": "Fresh or dry flowers/roots for tea and medicinal tinctures.",
        "granny_fanny": "True American native medicine — one of the best immune-boosting flowers you can grow on the homestead!",
        "companions": ["Yarrow", "Lavender", "Roses"],
        "no_go": []
    },
    {
        "common_name": "Snapdragon",
        "scientific_name": "Antirrhinum majus",
        "cultivar": "Rocket Mix",
        "type": "Hybrid",
        "growth_habit": "Upright (18-30 inches)",
        "method": "Starter recommended",
        "depth": "1/8 inch (surface sow)",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "2-3 per sq. ft.",
        "care": "Full sun; cool weather lover; pinch for bushiness; excellent cut flower.",
        "days_to_harvest": "60-70 days to bloom",
        "harvest_indicators": "Tall spikes with open dragon-mouth flowers in bright colors.",
        "yield_family_2": "6-8 plants",
        "yield_family_4": "12-16 plants",
        "preservation": "Fresh cut flowers; dry for arrangements.",
        "granny_fanny": "Kids love squeezing the 'dragon mouths' — these hybrids bloom non-stop and make gorgeous bouquets!",
        "companions": ["Tomatoes", "Cabbage", "Marigolds"],
        "no_go": []
    }
]

# ✅ Paste done! This gives you the first 8 flowers (mix of heirloom & hybrid, American, Latino/Mexican, and native influences).
# Reply with "next 8 flowers" when you're ready for flowers 9-16.
