# herb_data.py
# FIRST SECTION: Herbs 1-8
# Copy and paste this entire block into herb_data.py
# (It starts the list exactly as your GitHub repo expects)

herbs = [
    {
        "common_name": "Sweet Basil",
        "scientific_name": "Ocimum basilicum",
        "cultivar": "Genovese",
        "type": "Heirloom",
        "growth_habit": "Bushy (18-24 inches)",
        "method": "Starter recommended",
        "depth": "1/4 inch",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "2 per sq. ft.",
        "care": "Warmth lover; pinch tops for bushiness; consistent moisture; full sun.",
        "days_to_harvest": "60-70 days (to first harvest)",
        "harvest_indicators": "Large, bright green leaves before flowering.",
        "yield_family_2": "4 plants",
        "yield_family_4": "8 plants",
        "preservation": "Fresh, pesto, dried, or frozen in olive oil/ice cubes.",
        "granny_fanny": "Pinch the flowers off or it'll quit making leaves — keep it leafy all summer long!",
        "companions": ["Tomatoes", "Peppers", "Marigolds"],
        "no_go": ["Cucumbers"]
    },
    {
        "common_name": "Thai Basil",
        "scientific_name": "Ocimum basilicum",
        "cultivar": "Thai",
        "type": "Heirloom",
        "growth_habit": "Bushy (compact 12-18 inches)",
        "method": "Starter recommended",
        "depth": "1/4 inch",
        "spacing_traditional": "10-12 inches",
        "spacing_grid": "3 per sq. ft.",
        "care": "Full sun; loves heat and humidity; harvest often.",
        "days_to_harvest": "60-70 days",
        "harvest_indicators": "Purple stems and leaves; aromatic before flowering.",
        "yield_family_2": "3-4 plants",
        "yield_family_4": "6-8 plants",
        "preservation": "Fresh in Asian dishes; dries well for teas and spice blends.",
        "granny_fanny": "This Asian beauty brings that authentic Thai street-food flavor right to your homestead garden!",
        "companions": ["Tomatoes", "Peppers", "Eggplant"],
        "no_go": ["Cucumbers"]
    },
    {
        "common_name": "Cilantro",
        "scientific_name": "Coriandrum sativum",
        "cultivar": "Slow Bolt",
        "type": "Heirloom",
        "growth_habit": "Upright (12-18 inches)",
        "method": "Direct sow",
        "depth": "1/4 inch",
        "spacing_traditional": "6-8 inches",
        "spacing_grid": "4-6 per sq. ft.",
        "care": "Cool weather lover; succession plant every 2-3 weeks; bolt-resistant.",
        "days_to_harvest": "30-45 days (leaves), 90-100 days (seed)",
        "harvest_indicators": "Lush green leaves before bolting; seeds when brown and dry.",
        "yield_family_2": "6 plants",
        "yield_family_4": "12 plants",
        "preservation": "Fresh leaves, dried, or freeze in oil; seeds for coriander spice.",
        "granny_fanny": "Plant every 2 weeks — this Latino favorite bolts fast but keeps the salsa and guac coming all season!",
        "companions": ["Tomatoes", "Chiles", "Carrots"],
        "no_go": ["Fennel"]
    },
    {
        "common_name": "Italian Parsley",
        "scientific_name": "Petroselinum crispum",
        "cultivar": "Italian Flat Leaf",
        "type": "Heirloom",
        "growth_habit": "Upright (12-24 inches)",
        "method": "Starter recommended or direct sow",
        "depth": "1/4 inch",
        "spacing_traditional": "8-12 inches",
        "spacing_grid": "3 per sq. ft.",
        "care": "Cool to moderate temps; consistent moisture; full sun to part shade.",
        "days_to_harvest": "60-70 days",
        "harvest_indicators": "Large, flat, dark green leaves; cut outer stems first.",
        "yield_family_2": "4-6 plants",
        "yield_family_4": "8-12 plants",
        "preservation": "Fresh, dried, or frozen in ice cubes for soups and sauces.",
        "granny_fanny": "The real Italian flavor — flat leaf beats curly every time for cooking!",
        "companions": ["Tomatoes", "Peppers", "Asparagus"],
        "no_go": ["Carrots"]
    },
    {
        "common_name": "Dill",
        "scientific_name": "Anethum graveolens",
        "cultivar": "Bouquet",
        "type": "Heirloom",
        "growth_habit": "Upright (24-36 inches)",
        "method": "Direct sow",
        "depth": "1/4 inch",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "2 per sq. ft.",
        "care": "Full sun; well-drained soil; succession sow for continuous harvest.",
        "days_to_harvest": "40-60 days (leaves), 70-90 days (seed)",
        "harvest_indicators": "Feathery leaves before flowering; seeds when brown.",
        "yield_family_2": "3-4 plants",
        "yield_family_4": "6-8 plants",
        "preservation": "Fresh leaves, dried, or freeze; seeds for pickling.",
        "granny_fanny": "One plant will give you enough pickles for the whole neighborhood — and the butterflies love it!",
        "companions": ["Cucumbers", "Cabbage", "Onions"],
        "no_go": ["Fennel", "Tomatoes"]
    },
    {
        "common_name": "Greek Oregano",
        "scientific_name": "Origanum vulgare",
        "cultivar": "Greek",
        "type": "Heirloom",
        "growth_habit": "Bushy (12-18 inches)",
        "method": "Starter recommended",
        "depth": "1/4 inch",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "2 per sq. ft.",
        "care": "Full sun; drought tolerant once established; trim often.",
        "days_to_harvest": "60-80 days",
        "harvest_indicators": "Leaves before flowering; intense aroma when crushed.",
        "yield_family_2": "3 plants",
        "yield_family_4": "6 plants",
        "preservation": "Fresh, dried (hang bundles), or frozen.",
        "granny_fanny": "True Mediterranean flavor — this one makes your homemade pizza taste like it came from Naples!",
        "companions": ["Tomatoes", "Peppers", "Cabbage"],
        "no_go": ["Cucumbers"]
    },
    {
        "common_name": "Common Chives",
        "scientific_name": "Allium schoenoprasum",
        "cultivar": "Common",
        "type": "Heirloom",
        "growth_habit": "Clumping (12-18 inches)",
        "method": "Starter recommended or direct sow",
        "depth": "1/4 inch",
        "spacing_traditional": "8-12 inches",
        "spacing_grid": "4 per sq. ft.",
        "care": "Full sun to part shade; divide clumps every 3 years; cut regularly.",
        "days_to_harvest": "60-70 days",
        "harvest_indicators": "Hollow green stalks before flowering; edible purple blooms.",
        "yield_family_2": "4-6 clumps",
        "yield_family_4": "8-12 clumps",
        "preservation": "Fresh, dried, or frozen; flowers for vinegar.",
        "granny_fanny": "Snip and sprinkle on everything — the easiest perennial herb a homesteader can grow!",
        "companions": ["Carrots", "Tomatoes", "Roses"],
        "no_go": ["Beans", "Peas"]
    },
    {
        "common_name": "Rosemary",
        "scientific_name": "Salvia rosmarinus",
        "cultivar": "Tuscan Blue",
        "type": "Heirloom",
        "growth_habit": "Upright shrub (24-36 inches)",
        "method": "Starter recommended",
        "depth": "1/4 inch",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Full sun; well-drained soil; drought tolerant; protect in winter.",
        "days_to_harvest": "80-100 days (to first harvest)",
        "harvest_indicators": "Woody stems with needle-like leaves; strong piney aroma.",
        "yield_family_2": "2-3 plants",
        "yield_family_4": "4-6 plants",
        "preservation": "Fresh, dried, or frozen in oil; great for wreaths.",
        "granny_fanny": "This woody Mediterranean beauty is practically immortal — one plant will last you years!",
        "companions": ["Sage", "Carrots", "Cabbage"],
        "no_go": ["Cucumbers"]
    }
]

# ✅ Paste done! This gives you the first 8 herbs (mix of heirloom varieties with American, Latino, and Asian influences).
# Reply with "next 8 herbs" when you're ready for herbs 9-16.
