plants = [
    {"name":"Better Boy Tomato", "type":"Tomatoes", "pitch":"Reliable slicing tomato, disease resistant, great flavor.", "spacing":"24-36 inches", "depth":"Bury stem deep", "sun":"Full sun", "water":"Deep 2-3x/week", "harvest_days":"70-80 days", "yield":"15-25 lbs", "companions":["Basil","Marigold"], "avoid":["Potato"], "care":"Stake well", "harvest_notes":"Pick when deep red"},
    {"name":"Roma Tomato", "type":"Tomatoes", "pitch":"Perfect for sauces and canning.", "spacing":"18-24 inches", "depth":"Bury stem deep", "sun":"Full sun", "water":"Deep watering", "harvest_days":"75-85 days", "yield":"Excellent for preserving", "companions":["Basil"], "avoid":["Potato"], "care":"Less pruning", "harvest_notes":"When fully red"},
    {"name":"Sweet 100 Cherry Tomato", "type":"Tomatoes", "pitch":"Sweet, prolific cherry tomato — great for snacking.", "spacing":"18-24 inches", "depth":"Bury stem deep", "sun":"Full sun", "water":"Consistent", "harvest_days":"60-70 days", "yield":"Hundreds", "companions":["Basil"], "avoid":["Potato"], "care":"Trellis", "harvest_notes":"Bright red"},
    {"name":"California Wonder Bell Pepper", "type":"Peppers", "pitch":"Classic sweet bell pepper.", "spacing":"18-24 inches", "depth":"Same as pot", "sun":"Full sun", "water":"Consistent", "harvest_days":"75 days", "yield":"8-12", "companions":["Tomato"], "avoid":["Beans"], "care":"Warm soil", "harvest_notes":"Green or colored"},
    {"name":"Jalapeño Pepper", "type":"Peppers", "pitch":"Perfect heat, very productive.", "spacing":"12-18 inches", "depth":"Same as pot", "sun":"Full sun", "water":"Moderate", "harvest_days":"70 days", "yield":"Lots", "companions":["Tomato"], "avoid":["Beans"], "care":"Wear gloves", "harvest_notes":"Dark green"},
    {"name":"Sweet Italian Basil", "type":"Herbs", "pitch":"The pesto king — aromatic and prolific.", "spacing":"8-12 inches", "depth":"1/4 inch", "sun":"Full sun", "water":"Moderate", "harvest_days":"60 days", "yield":"Abundant", "companions":["Tomato"], "avoid":[], "care":"Pinch tops", "harvest_notes":"Use fresh"},
    {"name":"Cilantro", "type":"Herbs", "pitch":"Essential for Mexican and Asian dishes.", "spacing":"4-6 inches", "depth":"1/4 inch", "sun":"Partial", "water":"Moist", "harvest_days":"30-45 days", "yield":"Fast", "companions":["Tomato"], "avoid":[], "care":"Cool weather", "harvest_notes":"Bolts in heat"},
    {"name":"Lacinato Kale", "type":"Greens", "pitch":"Tender, cold-hardy, nutritious.", "spacing":"12-18 inches", "depth":"1/4 inch", "sun":"Full sun", "water":"Moderate", "harvest_days":"60 days", "yield":"Long season", "companions":["Onion"], "avoid":[], "care":"Frost improves flavor", "harvest_notes":"Baby leaves best"},
    {"name":"Collard Greens", "type":"Greens", "pitch":"Southern classic, very hardy.", "spacing":"18 inches", "depth":"1/4 inch", "sun":"Full sun", "water":"Moderate", "harvest_days":"70 days", "yield":"Continuous", "companions":["Onion"], "avoid":[], "care":"Harvest outer leaves", "harvest_notes":"Cook tender"},
    {"name":"Nantes Carrot", "type":"Roots", "pitch":"Sweet and crisp.", "spacing":"2-3 inches", "depth":"1/4 inch", "sun":"Full sun", "water":"Keep moist", "harvest_days":"65 days", "yield":"Uniform", "companions":["Lettuce"], "avoid":["Dill"], "care":"Loose soil", "harvest_notes":"Pull at size"},
    {"name":"Okra - Clemson Spineless", "type":"Vegetables", "pitch":"Heat-loving Southern favorite.", "spacing":"12-18 inches", "depth":"1 inch", "sun":"Full sun", "water":"Moderate", "harvest_days":"60 days", "yield":"Very high", "companions":["Peppers"], "avoid":[], "care":"Harvest young", "harvest_notes":"Every couple days"},
]
