plants = [

# ==================== TOMATOES ====================
{"name": "Brandywine Tomato", "type": "Tomatoes", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-9",
"pitch": "Large pink heirloom prized for exceptional flavor.",
"spacing": "30-36 inches", "row_spacing": "48 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "85-90",
"couple": "2 plants", "family4": "4 plants",
"start": "Start indoors 6-8 weeks before last frost",
"care": "Stake heavily; prune suckers; needs warm season",
"harvest_window": "August–September", "yield": "10-15 lbs per plant",
"companions": ["Basil", "Marigold"], "avoid": ["Potatoes"],
"granny_says": "Not the fastest, but oh honey the flavor.", "difficulty": "Intermediate", "tags": "heirloom, beefsteak"},

{"name": "San Marzano Tomato", "type": "Tomatoes", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-10",
"pitch": "Classic Italian paste tomato for sauces.",
"spacing": "24 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-10 days", "harvest_days": "80",
"couple": "3 plants", "family4": "6 plants",
"start": "Start indoors 6 weeks before last frost",
"care": "Stake; consistent watering",
"harvest_window": "July–September", "yield": "15-20 lbs per plant",
"companions": ["Basil"], "avoid": ["Potatoes"],
"granny_says": "This is your sauce tomato.", "difficulty": "Beginner", "tags": "paste"},

{"name": "Cherokee Purple Tomato", "type": "Tomatoes", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-9",
"pitch": "Dark heirloom with rich smoky flavor.",
"spacing": "30 inches", "row_spacing": "48 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "80",
"couple": "2 plants", "family4": "4 plants",
"start": "Start indoors 6 weeks before frost",
"care": "Needs staking and airflow",
"harvest_window": "July–September", "yield": "10-15 lbs per plant",
"companions": ["Basil"], "avoid": ["Potatoes"],
"granny_says": "Ugly fruit, beautiful taste.", "difficulty": "Intermediate", "tags": "heirloom"},

{"name": "Early Girl Tomato", "type": "Tomatoes", "heirloom_hybrid": "Hybrid", "recommended_zones": "4-10",
"pitch": "Fast-producing early slicing tomato.",
"spacing": "24 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-10 days", "harvest_days": "55-65",
"couple": "3 plants", "family4": "6 plants",
"start": "Start indoors 6 weeks early",
"care": "Stake; benefits from early feeding",
"harvest_window": "June–August", "yield": "15 lbs per plant",
"companions": ["Basil"], "avoid": ["Potatoes"],
"granny_says": "Gets you tomatoes before your neighbors.", "difficulty": "Beginner", "tags": "early"},

# ==================== PEPPERS ====================
{"name": "California Wonder Pepper", "type": "Peppers", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-10",
"pitch": "Classic bell pepper that turns red when ripe.",
"spacing": "18 inches", "row_spacing": "24-36 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "70-80",
"couple": "3 plants", "family4": "6 plants",
"start": "Start indoors 8 weeks before frost",
"care": "Warm soil; avoid cold nights",
"harvest_window": "Summer", "yield": "5-10 peppers per plant",
"companions": ["Basil"], "avoid": ["Fennel"],
"granny_says": "Wait for red if you want sweetness.", "difficulty": "Beginner", "tags": "bell"},

{"name": "Jalapeño M Pepper", "type": "Peppers", "heirloom_hybrid": "Hybrid", "recommended_zones": "5-10",
"pitch": "Standard medium-heat jalapeño.",
"spacing": "18 inches", "row_spacing": "24-36 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "65",
"couple": "3 plants", "family4": "6 plants",
"start": "Start indoors 8 weeks early",
"care": "Harvest green or red",
"harvest_window": "Summer", "yield": "25 peppers per plant",
"companions": ["Basil"], "avoid": ["Fennel"],
"granny_says": "Just enough heat to behave.", "difficulty": "Beginner", "tags": "spicy"},

{"name": "Shishito Pepper", "type": "Peppers", "heirloom_hybrid": "Heirloom", "recommended_zones": "6-10",
"pitch": "Japanese pepper, mostly mild with occasional heat.",
"spacing": "18 inches", "row_spacing": "24 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "60",
"couple": "3 plants", "family4": "6 plants",
"start": "Start indoors 8 weeks early",
"care": "Pick young fruits",
"harvest_window": "Summer", "yield": "30+ peppers per plant",
"companions": ["Basil"], "avoid": ["Fennel"],
"granny_says": "One in ten might bite back.", "difficulty": "Beginner", "tags": "asian"},

# ==================== ROOTS ====================
{"name": "Danvers Carrot", "type": "Roots", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Classic American carrot, good for heavy soil.",
"spacing": "2-3 inches", "row_spacing": "12-18 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "10-14 days", "harvest_days": "70",
"couple": "20 plants", "family4": "40 plants",
"start": "Direct sow early spring",
"care": "Thin seedlings; keep soil loose",
"harvest_window": "Spring–Fall", "yield": "1 lb per 5-10 ft row",
"companions": ["Onions"], "avoid": [],
"granny_says": "Don’t crowd them or they’ll twist.", "difficulty": "Beginner", "tags": "root"},

{"name": "Detroit Dark Red Beet", "type": "Roots", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Standard beet with strong roots and greens.",
"spacing": "3 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "5-10 days", "harvest_days": "55",
"couple": "12 plants", "family4": "24 plants",
"start": "Direct sow",
"care": "Thin early; consistent water",
"harvest_window": "Spring–Fall", "yield": "1/2 lb per foot",
"companions": ["Onions"], "avoid": [],
"granny_says": "Eat the greens too.", "difficulty": "Beginner", "tags": "root"},

# ==================== GREENS ====================
{"name": "Black Seeded Simpson Lettuce", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Loose leaf lettuce, quick and reliable.",
"spacing": "6-8 inches", "row_spacing": "12 inches", "sun": "Partial",
"sowing_depth": "Surface", "germination_time": "5-10 days", "harvest_days": "45",
"couple": "8 plants", "family4": "16 plants",
"start": "Direct sow early spring/fall",
"care": "Keep cool; succession plant",
"harvest_window": "Spring & Fall", "yield": "Continuous harvest",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Heat ends the party quick.", "difficulty": "Beginner", "tags": "cool season"},

{"name": "Lacinato Kale", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Italian kale, very cold hardy.",
"spacing": "12-18 inches", "row_spacing": "24 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "7-10 days", "harvest_days": "60",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow or transplant",
"care": "Harvest outer leaves",
"harvest_window": "Fall–Winter", "yield": "Continuous harvest",
"companions": ["Cabbage"], "avoid": [],
"granny_says": "Frost makes it sweeter.", "difficulty": "Beginner", "tags": "cold hardy"},

# ==================== HERBS ====================
{"name": "Genovese Basil", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-11",
"pitch": "Classic Italian basil for pesto.",
"spacing": "6-12 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "5-10 days", "harvest_days": "60",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow after frost",
"care": "Pinch regularly",
"harvest_window": "Summer", "yield": "Continuous harvest",
"companions": ["Tomatoes"], "avoid": [],
"granny_says": "Pinch it or it gets leggy.", "difficulty": "Beginner", "tags": "herb"},

{"name": "Cilantro Santo", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Slow-bolting cilantro variety.",
"spacing": "6 inches", "row_spacing": "12 inches", "sun": "Partial",
"sowing_depth": "1/4 inch", "germination_time": "7-10 days", "harvest_days": "45",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow cool weather",
"care": "Succession plant",
"harvest_window": "Spring & Fall", "yield": "Continuous harvest",
"companions": ["Tomatoes"], "avoid": [],
"granny_says": "It hates the heat.", "difficulty": "Beginner", "tags": "cool season"},

# ==================== VEGETABLES ====================
{"name": "Marketmore 76 Cucumber", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Reliable slicing cucumber.",
"spacing": "12 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "5-10 days", "harvest_days": "55",
"couple": "3 plants", "family4": "6 plants",
"start": "Direct sow after frost",
"care": "Trellis for best yield",
"harvest_window": "Summer", "yield": "10+ cucumbers per plant",
"companions": ["Beans"], "avoid": ["Potatoes"],
"granny_says": "Keep them picked.", "difficulty": "Beginner", "tags": "vining"},

{"name": "Black Beauty Zucchini", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Classic high-yield zucchini.",
"spacing": "24-36 inches", "row_spacing": "36-48 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "5-10 days", "harvest_days": "50",
"couple": "2 plants", "family4": "4 plants",
"start": "Direct sow after frost",
"care": "Harvest young fruits",
"harvest_window": "Summer", "yield": "20+ fruits per plant",
"companions": ["Corn"], "avoid": [],
"granny_says": "You’ll have too many.", "difficulty": "Beginner", "tags": "high yield"},

# ==================== FLOWERS ====================
{"name": "French Marigold", "type": "Flowers", "heirloom_hybrid": "Hybrid", "recommended_zones": "5-11",
"pitch": "Companion flower that deters pests.",
"spacing": "8-12 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "Surface", "germination_time": "5-10 days", "harvest_days": "60",
"couple": "6 plants", "family4": "10 plants",
"start": "Direct sow",
"care": "Deadhead blooms",
"harvest_window": "All season", "yield": "Continuous blooms",
"companions": ["Tomatoes"], "avoid": [],
"granny_says": "Pretty and useful.", "difficulty": "Beginner", "tags": "companion"},

]
plants += [

# ==================== TOMATOES ====================
{"name": "Big Beef Tomato", "type": "Tomatoes", "heirloom_hybrid": "Hybrid", "recommended_zones": "5-10",
"pitch": "Large, disease-resistant beefsteak with excellent yield.",
"spacing": "30-36 inches", "row_spacing": "48 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-10 days", "harvest_days": "70-75",
"couple": "2-3 plants", "family4": "4-6 plants",
"start": "Start indoors 6 weeks before last frost",
"care": "Strong staking required; prune for airflow",
"harvest_window": "July–September", "yield": "20-30 lbs per plant",
"companions": ["Basil"], "avoid": ["Potatoes"],
"granny_says": "Big fruit and plenty of it.", "difficulty": "Beginner", "tags": "hybrid, high yield"},

{"name": "Roma VF Tomato", "type": "Tomatoes", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-10",
"pitch": "Classic paste tomato for sauces and canning.",
"spacing": "18-24 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-10 days", "harvest_days": "75",
"couple": "3 plants", "family4": "6 plants",
"start": "Start indoors 6 weeks before frost",
"care": "Determinate; minimal pruning",
"harvest_window": "July–September", "yield": "15-25 lbs per plant",
"companions": ["Basil"], "avoid": ["Potatoes"],
"granny_says": "Good for a pantry full of jars.", "difficulty": "Beginner", "tags": "paste"},

# ==================== PEPPERS ====================
{"name": "Poblano Pepper", "type": "Peppers", "heirloom_hybrid": "Heirloom", "recommended_zones": "6-10",
"pitch": "Mild pepper used for stuffing and roasting.",
"spacing": "18-24 inches", "row_spacing": "24-36 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "75",
"couple": "2 plants", "family4": "4 plants",
"start": "Start indoors 8 weeks early",
"care": "Prefers warm nights",
"harvest_window": "Summer", "yield": "10-20 peppers per plant",
"companions": ["Basil"], "avoid": ["Fennel"],
"granny_says": "Roast it slow.", "difficulty": "Intermediate", "tags": "mexican"},

{"name": "Hungarian Wax Pepper", "type": "Peppers", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-9",
"pitch": "Medium-hot yellow pepper great for pickling.",
"spacing": "18 inches", "row_spacing": "24-36 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "70",
"couple": "3 plants", "family4": "6 plants",
"start": "Start indoors 8 weeks early",
"care": "Harvest young for mild flavor",
"harvest_window": "Summer", "yield": "20+ peppers per plant",
"companions": ["Basil"], "avoid": ["Fennel"],
"granny_says": "Good in a jar.", "difficulty": "Beginner", "tags": "pickling"},

# ==================== ROOTS ====================
{"name": "Nantes Carrot", "type": "Roots", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Sweet, cylindrical carrot with tender texture.",
"spacing": "2-3 inches", "row_spacing": "12-18 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "10-14 days", "harvest_days": "65",
"couple": "20 plants", "family4": "40 plants",
"start": "Direct sow early spring",
"care": "Loose soil required",
"harvest_window": "Spring–Fall", "yield": "1 lb per 5-10 ft row",
"companions": ["Onions"], "avoid": [],
"granny_says": "Loose soil, straight roots.", "difficulty": "Beginner", "tags": "root"},

{"name": "French Breakfast Radish", "type": "Roots", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Fast-growing mild radish.",
"spacing": "2 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "3-7 days", "harvest_days": "25-30",
"couple": "20 plants", "family4": "40 plants",
"start": "Direct sow",
"care": "Keep moist for mild flavor",
"harvest_window": "Spring & Fall", "yield": "1 lb per 10 ft row",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Quick reward crop.", "difficulty": "Beginner", "tags": "fast"},

# ==================== GREENS ====================
{"name": "Buttercrunch Lettuce", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Tender butterhead lettuce.",
"spacing": "8-12 inches", "row_spacing": "12 inches", "sun": "Partial",
"sowing_depth": "Surface", "germination_time": "7-10 days", "harvest_days": "50",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow cool weather",
"care": "Keep soil moist",
"harvest_window": "Spring & Fall", "yield": "Heads or leaf harvest",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Soft and sweet.", "difficulty": "Beginner", "tags": "cool season"},

{"name": "Red Russian Kale", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Cold-hardy kale with tender leaves.",
"spacing": "12-18 inches", "row_spacing": "24 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "5-10 days", "harvest_days": "55",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow or transplant",
"care": "Harvest outer leaves",
"harvest_window": "Fall–Winter", "yield": "Continuous harvest",
"companions": ["Cabbage"], "avoid": [],
"granny_says": "Cold makes it better.", "difficulty": "Beginner", "tags": "cold hardy"},

# ==================== HERBS ====================
{"name": "Italian Flat Leaf Parsley", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Flavorful parsley used in cooking.",
"spacing": "6-8 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "14-21 days", "harvest_days": "70",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow or transplant",
"care": "Slow to germinate; keep moist",
"harvest_window": "Spring–Fall", "yield": "Continuous harvest",
"companions": ["Tomatoes"], "avoid": [],
"granny_says": "Takes patience.", "difficulty": "Beginner", "tags": "herb"},

{"name": "Bouquet Dill", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Classic dill for pickling.",
"spacing": "12 inches", "row_spacing": "18 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "50",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow",
"care": "Does not transplant well",
"harvest_window": "Summer", "yield": "Leaves and seeds",
"companions": ["Cabbage"], "avoid": ["Carrots"],
"granny_says": "Plant it where it stays.", "difficulty": "Beginner", "tags": "herb"},

# ==================== VEGETABLES ====================
{"name": "Straight Eight Cucumber", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Classic straight slicing cucumber.",
"spacing": "12 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "5-10 days", "harvest_days": "55",
"couple": "3 plants", "family4": "6 plants",
"start": "Direct sow",
"care": "Trellis improves yield",
"harvest_window": "Summer", "yield": "10+ per plant",
"companions": ["Beans"], "avoid": ["Potatoes"],
"granny_says": "Keep picking them.", "difficulty": "Beginner", "tags": "vining"},

{"name": "Golden Bantam Corn", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Classic sweet corn variety.",
"spacing": "12 inches", "row_spacing": "30 inches", "sun": "Full sun",
"sowing_depth": "1-1.5 inches", "germination_time": "7-10 days", "harvest_days": "75",
"couple": "12 plants", "family4": "24 plants",
"start": "Direct sow in blocks",
"care": "Needs block planting for pollination",
"harvest_window": "Summer", "yield": "1-2 ears per plant",
"companions": ["Beans"], "avoid": [],
"granny_says": "Plant in blocks, not rows.", "difficulty": "Intermediate", "tags": "corn"},

# ==================== FLOWERS ====================
{"name": "Zinnia Giant", "type": "Flowers", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Large colorful flowers for pollinators.",
"spacing": "12 inches", "row_spacing": "12-18 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "5-7 days", "harvest_days": "60",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow",
"care": "Deadhead blooms",
"harvest_window": "Summer", "yield": "Continuous blooms",
"companions": ["Vegetables"], "avoid": [],
"granny_says": "They love heat.", "difficulty": "Beginner", "tags": "pollinator"},

]
plants += [

# ==================== BEANS ====================
{"name": "Blue Lake Bush Bean", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Classic bush green bean with excellent flavor.",
"spacing": "3-4 inches", "row_spacing": "18-24 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "6-10 days", "harvest_days": "55",
"couple": "10 plants", "family4": "20 plants",
"start": "Direct sow after frost",
"care": "Pick frequently to extend harvest",
"harvest_window": "Summer", "yield": "1/2 lb per plant",
"companions": ["Corn"], "avoid": ["Onions"],
"granny_says": "The more you pick, the more you get.", "difficulty": "Beginner", "tags": "bush bean"},

{"name": "Kentucky Wonder Pole Bean", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Heirloom pole bean with heavy yields.",
"spacing": "6 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "6-10 days", "harvest_days": "65",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow",
"care": "Needs trellis or pole",
"harvest_window": "Summer", "yield": "1 lb per plant",
"companions": ["Corn"], "avoid": ["Onions"],
"granny_says": "Give it something to climb.", "difficulty": "Beginner", "tags": "pole bean"},

# ==================== SQUASH ====================
{"name": "Waltham Butternut Squash", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Winter squash with long storage life.",
"spacing": "36 inches", "row_spacing": "72 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "95-110",
"couple": "2 plants", "family4": "4 plants",
"start": "Direct sow after frost",
"care": "Needs space; protect from squash bugs",
"harvest_window": "Fall", "yield": "4-6 fruits per plant",
"companions": ["Corn"], "avoid": [],
"granny_says": "Stores all winter.", "difficulty": "Intermediate", "tags": "winter squash"},

{"name": "Table Queen Acorn Squash", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Compact acorn squash with sweet flesh.",
"spacing": "36 inches", "row_spacing": "72 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "80-90",
"couple": "2 plants", "family4": "4 plants",
"start": "Direct sow",
"care": "Harvest before frost",
"harvest_window": "Fall", "yield": "4-5 fruits per plant",
"companions": ["Corn"], "avoid": [],
"granny_says": "Perfect stuffed.", "difficulty": "Beginner", "tags": "winter squash"},

# ==================== CORN ====================
{"name": "Silver Queen Corn", "type": "Vegetables", "heirloom_hybrid": "Hybrid", "recommended_zones": "4-9",
"pitch": "Popular white sweet corn variety.",
"spacing": "12 inches", "row_spacing": "30 inches", "sun": "Full sun",
"sowing_depth": "1-1.5 inches", "germination_time": "7-10 days", "harvest_days": "90",
"couple": "12 plants", "family4": "24 plants",
"start": "Direct sow in blocks",
"care": "Needs pollination block planting",
"harvest_window": "Summer", "yield": "1-2 ears per plant",
"companions": ["Beans"], "avoid": [],
"granny_says": "Don’t plant just one row.", "difficulty": "Intermediate", "tags": "corn"},

# ==================== ROOTS ====================
{"name": "Purple Top White Globe Turnip", "type": "Roots", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-9",
"pitch": "Classic turnip for roots and greens.",
"spacing": "4 inches", "row_spacing": "12-18 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "5-10 days", "harvest_days": "50",
"couple": "12 plants", "family4": "24 plants",
"start": "Direct sow",
"care": "Harvest young for best flavor",
"harvest_window": "Spring & Fall", "yield": "1 lb per 10 ft row",
"companions": ["Peas"], "avoid": [],
"granny_says": "Don’t let them get woody.", "difficulty": "Beginner", "tags": "root"},

{"name": "Hakurei Turnip", "type": "Roots", "heirloom_hybrid": "Hybrid", "recommended_zones": "4-9",
"pitch": "Sweet Japanese turnip eaten raw or cooked.",
"spacing": "2-3 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "5-7 days", "harvest_days": "35-40",
"couple": "20 plants", "family4": "40 plants",
"start": "Direct sow",
"care": "Fast grower; harvest small",
"harvest_window": "Spring & Fall", "yield": "1 lb per 5 ft row",
"companions": ["Peas"], "avoid": [],
"granny_says": "Sweet as an apple when young.", "difficulty": "Beginner", "tags": "fast"},

# ==================== GREENS ====================
{"name": "Georgia Southern Collards", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "6-10",
"pitch": "Heat-tolerant collard green.",
"spacing": "18 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "7-10 days", "harvest_days": "75",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow or transplant",
"care": "Harvest outer leaves",
"harvest_window": "Fall–Winter", "yield": "Continuous harvest",
"companions": ["Onions"], "avoid": [],
"granny_says": "Gets better after frost.", "difficulty": "Beginner", "tags": "southern"},

{"name": "Bloomsdale Spinach", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-9",
"pitch": "Savoyed spinach for cool seasons.",
"spacing": "3-6 inches", "row_spacing": "12 inches", "sun": "Partial",
"sowing_depth": "1/2 inch", "germination_time": "7-14 days", "harvest_days": "45",
"couple": "8 plants", "family4": "16 plants",
"start": "Direct sow early",
"care": "Bolts in heat",
"harvest_window": "Spring & Fall", "yield": "Continuous harvest",
"companions": ["Radish"], "avoid": [],
"granny_says": "Plant it early.", "difficulty": "Beginner", "tags": "cool season"},

# ==================== HERBS ====================
{"name": "English Thyme", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-9",
"pitch": "Perennial herb with strong flavor.",
"spacing": "12 inches", "row_spacing": "18 inches", "sun": "Full sun",
"sowing_depth": "Surface", "germination_time": "10-14 days", "harvest_days": "90",
"couple": "2 plants", "family4": "4 plants",
"start": "Start indoors or transplant",
"care": "Prefers dry soil",
"harvest_window": "Year-round mild climates", "yield": "Continuous harvest",
"companions": ["Cabbage"], "avoid": [],
"granny_says": "Does better with less fuss.", "difficulty": "Beginner", "tags": "perennial"},

{"name": "Greek Oregano", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-10",
"pitch": "Strong-flavored oregano for Mediterranean cooking.",
"spacing": "12-18 inches", "row_spacing": "18 inches", "sun": "Full sun",
"sowing_depth": "Surface", "germination_time": "7-14 days", "harvest_days": "80",
"couple": "2 plants", "family4": "4 plants",
"start": "Transplant or direct sow",
"care": "Cut back to encourage growth",
"harvest_window": "Summer", "yield": "Continuous harvest",
"companions": ["Peppers"], "avoid": [],
"granny_says": "Sun and dry feet.", "difficulty": "Beginner", "tags": "herb"},

# ==================== VEGETABLES ====================
{"name": "Clemson Spineless Okra", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "6-11",
"pitch": "Classic okra with tender pods.",
"spacing": "12-18 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "55-65",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow in warm soil",
"care": "Needs heat",
"harvest_window": "Summer", "yield": "20+ pods per plant",
"companions": ["Peppers"], "avoid": [],
"granny_says": "Wait for warm soil.", "difficulty": "Beginner", "tags": "heat loving"},

{"name": "Sugar Baby Watermelon", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "7-11",
"pitch": "Small watermelon for shorter seasons.",
"spacing": "36 inches", "row_spacing": "72 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "75",
"couple": "1-2 plants", "family4": "3 plants",
"start": "Direct sow",
"care": "Needs heat and space",
"harvest_window": "Summer", "yield": "2-4 melons per plant",
"companions": ["Corn"], "avoid": [],
"granny_says": "Give it room to sprawl.", "difficulty": "Intermediate", "tags": "melon"},

# ==================== FLOWERS ====================
{"name": "Mammoth Sunflower", "type": "Flowers", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Giant sunflower for seeds and pollinators.",
"spacing": "18-24 inches", "row_spacing": "24 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "80",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow",
"care": "Needs staking in wind",
"harvest_window": "Summer", "yield": "1 large head per plant",
"companions": ["Corn"], "avoid": [],
"granny_says": "Tall and proud.", "difficulty": "Beginner", "tags": "pollinator"},

{"name": "Cosmos Sensation", "type": "Flowers", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Easy-growing flower for pollinators.",
"spacing": "12 inches", "row_spacing": "18 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "5-10 days", "harvest_days": "60",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow",
"care": "Thrives in poor soil",
"harvest_window": "Summer", "yield": "Continuous blooms",
"companions": ["Vegetables"], "avoid": [],
"granny_says": "Does better if you ignore it.", "difficulty": "Beginner", "tags": "pollinator"},

]
plants += [

# ==================== BEANS & PEAS ====================
{"name": "Provider Bush Bean", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Cold-tolerant bush bean that produces early.",
"spacing": "3-4 inches", "row_spacing": "18-24 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "6-10 days", "harvest_days": "50",
"couple": "10 plants", "family4": "20 plants",
"start": "Direct sow after soil warms",
"care": "Harvest frequently",
"harvest_window": "Late spring–summer", "yield": "1/2 lb per plant",
"companions": ["Corn"], "avoid": ["Onions"],
"granny_says": "Handles cool soil better than most.", "difficulty": "Beginner", "tags": "bush bean"},

{"name": "Sugar Snap Pea", "type": "Vegetables", "heirloom_hybrid": "Hybrid", "recommended_zones": "3-9",
"pitch": "Sweet edible-pod pea.",
"spacing": "2 inches", "row_spacing": "18-24 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-14 days", "harvest_days": "60",
"couple": "12 plants", "family4": "24 plants",
"start": "Direct sow early spring",
"care": "Provide trellis",
"harvest_window": "Spring", "yield": "1/2 lb per plant",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Plant as soon as the ground thaws.", "difficulty": "Beginner", "tags": "pea"},

# ==================== SQUASH & MELONS ====================
{"name": "Costata Romanesco Zucchini", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Italian zucchini with ridged fruit and excellent flavor.",
"spacing": "24-36 inches", "row_spacing": "36-48 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "5-10 days", "harvest_days": "55",
"couple": "2 plants", "family4": "4 plants",
"start": "Direct sow",
"care": "Harvest frequently",
"harvest_window": "Summer", "yield": "15-20 fruits per plant",
"companions": ["Corn"], "avoid": [],
"granny_says": "Better flavor than most zucchini.", "difficulty": "Beginner", "tags": "summer squash"},

{"name": "Crimson Sweet Watermelon", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "7-11",
"pitch": "Large, sweet watermelon variety.",
"spacing": "36 inches", "row_spacing": "72 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "85",
"couple": "1-2 plants", "family4": "3 plants",
"start": "Direct sow in warm soil",
"care": "Needs long, hot season",
"harvest_window": "Summer", "yield": "3-5 melons per plant",
"companions": ["Corn"], "avoid": [],
"granny_says": "Heat is everything.", "difficulty": "Intermediate", "tags": "melon"},

# ==================== ROOTS ====================
{"name": "Chioggia Beet", "type": "Roots", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Italian beet with red-and-white rings.",
"spacing": "3 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "5-10 days", "harvest_days": "55",
"couple": "12 plants", "family4": "24 plants",
"start": "Direct sow",
"care": "Keep soil moist",
"harvest_window": "Spring–Fall", "yield": "1/2 lb per foot",
"companions": ["Onions"], "avoid": [],
"granny_says": "Pretty inside and out.", "difficulty": "Beginner", "tags": "root"},

{"name": "White Icicle Radish", "type": "Roots", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Long white radish with mild flavor.",
"spacing": "2 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "3-7 days", "harvest_days": "30",
"couple": "20 plants", "family4": "40 plants",
"start": "Direct sow",
"care": "Harvest promptly",
"harvest_window": "Spring & Fall", "yield": "1 lb per 10 ft row",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Don’t let them sit too long.", "difficulty": "Beginner", "tags": "fast"},

# ==================== GREENS ====================
{"name": "Arugula Rocket", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Peppery salad green.",
"spacing": "4-6 inches", "row_spacing": "12 inches", "sun": "Partial",
"sowing_depth": "1/4 inch", "germination_time": "5-7 days", "harvest_days": "30",
"couple": "8 plants", "family4": "16 plants",
"start": "Direct sow cool weather",
"care": "Bolts in heat",
"harvest_window": "Spring & Fall", "yield": "Continuous harvest",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Quick and spicy.", "difficulty": "Beginner", "tags": "cool season"},

{"name": "Fordhook Swiss Chard", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Large leafy green with white stems.",
"spacing": "12 inches", "row_spacing": "18-24 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "7-10 days", "harvest_days": "55",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow or transplant",
"care": "Harvest outer leaves",
"harvest_window": "Spring–Fall", "yield": "Continuous harvest",
"companions": ["Beans"], "avoid": [],
"granny_says": "Keeps going all season.", "difficulty": "Beginner", "tags": "leafy"},

# ==================== HERBS ====================
{"name": "Tuscan Blue Rosemary", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "7-10",
"pitch": "Upright rosemary with strong aroma.",
"spacing": "24-36 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "Surface", "germination_time": "14-21 days", "harvest_days": "90",
"couple": "1 plant", "family4": "2 plants",
"start": "Transplant",
"care": "Needs well-drained soil",
"harvest_window": "Year-round warm climates", "yield": "Continuous harvest",
"companions": ["Cabbage"], "avoid": [],
"granny_says": "Hates wet feet.", "difficulty": "Intermediate", "tags": "perennial"},

{"name": "Common Sage", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-9",
"pitch": "Classic herb for poultry dishes.",
"spacing": "18 inches", "row_spacing": "24 inches", "sun": "Full sun",
"sowing_depth": "Surface", "germination_time": "10-14 days", "harvest_days": "75",
"couple": "2 plants", "family4": "4 plants",
"start": "Transplant or direct sow",
"care": "Prune regularly",
"harvest_window": "Summer", "yield": "Continuous harvest",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Strong flavor, use lightly.", "difficulty": "Beginner", "tags": "herb"},

# ==================== VEGETABLES ====================
{"name": "Spaghetti Squash", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Winter squash with stringy flesh.",
"spacing": "36 inches", "row_spacing": "72 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "90",
"couple": "2 plants", "family4": "4 plants",
"start": "Direct sow",
"care": "Needs space",
"harvest_window": "Fall", "yield": "3-5 fruits per plant",
"companions": ["Corn"], "avoid": [],
"granny_says": "Strange but useful.", "difficulty": "Beginner", "tags": "winter squash"},

{"name": "Honeydew Green Flesh Melon", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "7-11",
"pitch": "Sweet melon with smooth rind.",
"spacing": "36 inches", "row_spacing": "72 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "85",
"couple": "1-2 plants", "family4": "3 plants",
"start": "Direct sow warm soil",
"care": "Needs long season",
"harvest_window": "Summer", "yield": "3-4 melons per plant",
"companions": ["Corn"], "avoid": [],
"granny_says": "Sun and patience.", "difficulty": "Intermediate", "tags": "melon"},

# ==================== FLOWERS ====================
{"name": "Nasturtium Alaska", "type": "Flowers", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Edible flower and pest deterrent.",
"spacing": "10-12 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "55",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow",
"care": "Poor soil preferred",
"harvest_window": "Summer", "yield": "Continuous blooms",
"companions": ["Vegetables"], "avoid": [],
"granny_says": "Don’t overfeed it.", "difficulty": "Beginner", "tags": "edible"},

{"name": "Calendula Pacific Beauty", "type": "Flowers", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Bright medicinal flower.",
"spacing": "10-12 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "5-10 days", "harvest_days": "50",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow",
"care": "Deadhead regularly",
"harvest_window": "Spring–Fall", "yield": "Continuous blooms",
"companions": ["Vegetables"], "avoid": [],
"granny_says": "Good for the bees and you.", "difficulty": "Beginner", "tags": "medicinal"},

]
plants += [

# ==================== HERBS ====================
{"name": "Spearmint", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Fast-growing mint for teas and cooking.",
"spacing": "18-24 inches", "row_spacing": "24 inches", "sun": "Partial",
"sowing_depth": "Surface", "germination_time": "10-14 days", "harvest_days": "60",
"couple": "1 plant", "family4": "2 plants",
"start": "Transplant or container plant",
"care": "Spreads aggressively; best contained",
"harvest_window": "Spring–Fall", "yield": "Continuous harvest",
"companions": ["Cabbage"], "avoid": [],
"granny_says": "Put it in a pot or it’ll take over.", "difficulty": "Beginner", "tags": "perennial"},

{"name": "Garlic Chives", "type": "Herbs", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-9",
"pitch": "Mild garlic-flavored herb.",
"spacing": "6-12 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "75",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow or transplant",
"care": "Cut regularly",
"harvest_window": "Spring–Fall", "yield": "Continuous harvest",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Comes back every year.", "difficulty": "Beginner", "tags": "perennial"},

# ==================== ROOTS ====================
{"name": "Golden Beet", "type": "Roots", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Mild, sweet yellow beet.",
"spacing": "3 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "5-10 days", "harvest_days": "55",
"couple": "12 plants", "family4": "24 plants",
"start": "Direct sow",
"care": "Keep soil moist",
"harvest_window": "Spring–Fall", "yield": "1/2 lb per foot",
"companions": ["Onions"], "avoid": [],
"granny_says": "Less earthy than red beets.", "difficulty": "Beginner", "tags": "root"},

{"name": "Cherry Belle Radish", "type": "Roots", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-10",
"pitch": "Classic round red radish.",
"spacing": "2 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/2 inch", "germination_time": "3-7 days", "harvest_days": "25",
"couple": "20 plants", "family4": "40 plants",
"start": "Direct sow",
"care": "Harvest quickly",
"harvest_window": "Spring & Fall", "yield": "1 lb per 10 ft row",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Fast and forgiving.", "difficulty": "Beginner", "tags": "fast"},

# ==================== GREENS ====================
{"name": "Romaine Parris Island Lettuce", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-9",
"pitch": "Crisp romaine lettuce variety.",
"spacing": "10-12 inches", "row_spacing": "12 inches", "sun": "Partial",
"sowing_depth": "Surface", "germination_time": "5-10 days", "harvest_days": "65",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow cool weather",
"care": "Keep soil cool",
"harvest_window": "Spring & Fall", "yield": "Heads or leaves",
"companions": ["Carrots"], "avoid": [],
"granny_says": "Perfect for a Caesar.", "difficulty": "Beginner", "tags": "lettuce"},

{"name": "Mustard Greens Southern Giant", "type": "Greens", "heirloom_hybrid": "Heirloom", "recommended_zones": "6-10",
"pitch": "Spicy leafy green.",
"spacing": "6-12 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "5-10 days", "harvest_days": "40",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow",
"care": "Harvest young leaves",
"harvest_window": "Spring–Fall", "yield": "Continuous harvest",
"companions": ["Onions"], "avoid": [],
"granny_says": "A little bite to it.", "difficulty": "Beginner", "tags": "greens"},

# ==================== VEGETABLES ====================
{"name": "Eggplant Black Beauty", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "5-10",
"pitch": "Classic large purple eggplant.",
"spacing": "24 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1/4 inch", "germination_time": "7-14 days", "harvest_days": "75",
"couple": "2 plants", "family4": "4 plants",
"start": "Start indoors 8 weeks early",
"care": "Needs heat and rich soil",
"harvest_window": "Summer", "yield": "6-10 fruits per plant",
"companions": ["Peppers"], "avoid": [],
"granny_says": "Treat it like a pepper.", "difficulty": "Intermediate", "tags": "nightshade"},

{"name": "Okra Red Burgundy", "type": "Vegetables", "heirloom_hybrid": "Heirloom", "recommended_zones": "6-11",
"pitch": "Striking red okra variety.",
"spacing": "12-18 inches", "row_spacing": "36 inches", "sun": "Full sun",
"sowing_depth": "1 inch", "germination_time": "7-10 days", "harvest_days": "60",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow warm soil",
"care": "Harvest pods young",
"harvest_window": "Summer", "yield": "20+ pods per plant",
"companions": ["Peppers"], "avoid": [],
"granny_says": "Heat is its friend.", "difficulty": "Beginner", "tags": "okra"},

# ==================== FLOWERS ====================
{"name": "Purple Coneflower", "type": "Flowers", "heirloom_hybrid": "Heirloom", "recommended_zones": "3-9",
"pitch": "Native pollinator flower.",
"spacing": "18 inches", "row_spacing": "24 inches", "sun": "Full sun",
"sowing_depth": "Surface", "germination_time": "10-20 days", "harvest_days": "90",
"couple": "4 plants", "family4": "8 plants",
"start": "Direct sow or transplant",
"care": "Drought tolerant once established",
"harvest_window": "Summer", "yield": "Perennial blooms",
"companions": ["Vegetables"], "avoid": [],
"granny_says": "Comes back every year.", "difficulty": "Beginner", "tags": "native"},

{"name": "Sweet Alyssum", "type": "Flowers", "heirloom_hybrid": "Heirloom", "recommended_zones": "4-10",
"pitch": "Low-growing pollinator flower.",
"spacing": "6-8 inches", "row_spacing": "12 inches", "sun": "Full sun",
"sowing_depth": "Surface", "germination_time": "5-10 days", "harvest_days": "45",
"couple": "6 plants", "family4": "12 plants",
"start": "Direct sow",
"care": "Trim for rebloom",
"harvest_window": "Spring–Fall", "yield": "Continuous blooms",
"companions": ["Vegetables"], "avoid": [],
"granny_says": "Bees love it.", "difficulty": "Beginner", "tags": "pollinator"},

]