# vegetable_data.py
# FIRST SECTION: Vegetables 1-8
# Copy and paste this entire block into vegetable_data.py
# (It starts the list exactly as your GitHub repo expects)

vegetables = [
    {
        "common_name": "Cherokee Purple Tomato",
        "scientific_name": "Solanum lycopersicum",
        "cultivar": "Cherokee Purple",
        "type": "Heirloom",
        "growth_habit": "Indeterminate (Vining - needs sturdy trellis)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Bury stems (starters)",
        "spacing_traditional": "24-36 inches",
        "spacing_grid": "1 per sq. ft. (Requires aggressive pruning)",
        "care": "Heavy feeder; sturdy staking; water base (avoid blight).",
        "days_to_harvest": "80-90 days",
        "harvest_indicators": "Deep dusky rose color; slight give.",
        "yield_family_2": "2 plants",
        "yield_family_4": "4-6 plants",
        "preservation": "Best fresh (fresh eating/sauce). Skin too tough for long canning.",
        "granny_fanny": "Don't you dare put these in the fridge! It kills the flavor faster than a late frost.",
        "companions": ["Basil", "Marigolds", "Parsley", "Chives"],
        "no_go": ["Corn", "Potatoes", "Fennel"]
    },
    {
        "common_name": "Brandywine Tomato",
        "scientific_name": "Solanum lycopersicum",
        "cultivar": "Brandywine",
        "type": "Heirloom",
        "growth_habit": "Indeterminate (Vining - needs sturdy trellis)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Bury stems (starters)",
        "spacing_traditional": "24-36 inches",
        "spacing_grid": "1 per sq. ft. (Requires aggressive pruning)",
        "care": "Heavy feeder; sturdy staking; consistent moisture to prevent cracking.",
        "days_to_harvest": "85-100 days",
        "harvest_indicators": "Large pink-red fruits with green shoulders; soft when ripe.",
        "yield_family_2": "2-3 plants",
        "yield_family_4": "5-7 plants",
        "preservation": "Excellent for fresh eating and sauces; can be canned or frozen.",
        "granny_fanny": "This old Pennsylvania Dutch favorite is worth the wait — the flavor is worth its weight in gold!",
        "companions": ["Basil", "Marigolds", "Carrots"],
        "no_go": ["Potatoes", "Fennel", "Corn"]
    },
    {
        "common_name": "Celebrity Tomato",
        "scientific_name": "Solanum lycopersicum",
        "cultivar": "Celebrity",
        "type": "Hybrid",
        "growth_habit": "Determinate (Bush - good for containers)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Bury stems (starters)",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Heavy feeder; stake or cage; disease resistant (VFNT).",
        "days_to_harvest": "70-75 days",
        "harvest_indicators": "Red, round, 8 oz fruits; firm when ripe.",
        "yield_family_2": "3 plants",
        "yield_family_4": "6-8 plants",
        "preservation": "Great for fresh eating, canning, sauces, and drying.",
        "granny_fanny": "This hybrid is a reliable producer even when the weather turns ornery — perfect for busy homesteaders!",
        "companions": ["Basil", "Marigolds"],
        "no_go": ["Potatoes", "Fennel"]
    },
    {
        "common_name": "Better Boy Tomato",
        "scientific_name": "Solanum lycopersicum",
        "cultivar": "Better Boy",
        "type": "Hybrid",
        "growth_habit": "Indeterminate (Vining - needs sturdy trellis)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Bury stems (starters)",
        "spacing_traditional": "24-36 inches",
        "spacing_grid": "1 per sq. ft. (Requires aggressive pruning)",
        "care": "Heavy feeder; sturdy staking; resistant to cracking and disease.",
        "days_to_harvest": "70-75 days",
        "harvest_indicators": "Large red, smooth fruits; firm with slight give.",
        "yield_family_2": "2 plants",
        "yield_family_4": "4-6 plants",
        "preservation": "Excellent for slicing fresh, sauces, and canning.",
        "granny_fanny": "Boy, does this one deliver — big, juicy tomatoes all summer long without the fuss!",
        "companions": ["Basil", "Marigolds", "Onions"],
        "no_go": ["Potatoes", "Corn"]
    },
    {
        "common_name": "Poblano Pepper",
        "scientific_name": "Capsicum annuum",
        "cultivar": "Poblano",
        "type": "Heirloom",
        "growth_habit": "Bushy (2-3 ft tall)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Transplant starters",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Warm soil lover; consistent water; mulch to retain moisture.",
        "days_to_harvest": "75-85 days",
        "harvest_indicators": "Dark green (or red when ripe), 4-6 inch heart-shaped fruits.",
        "yield_family_2": "3-4 plants",
        "yield_family_4": "6-8 plants",
        "preservation": "Best fresh (stuffing/roasting) or dried into ancho chiles; freeze well.",
        "granny_fanny": "These mild Mexican beauties make the best chile rellenos — harvest green for mild heat!",
        "companions": ["Basil", "Marigolds", "Onions"],
        "no_go": ["Fennel", "Kohlrabi"]
    },
    {
        "common_name": "Jalapeño Pepper",
        "scientific_name": "Capsicum annuum",
        "cultivar": "Jalapeño",
        "type": "Heirloom",
        "growth_habit": "Bushy (2-3 ft tall)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Transplant starters",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Full sun; moderate water; pick often to encourage production.",
        "days_to_harvest": "70-80 days",
        "harvest_indicators": "Dark green (or red when ripe), 3-4 inch fruits with slight striping.",
        "yield_family_2": "4 plants",
        "yield_family_4": "8-10 plants",
        "preservation": "Fresh, pickled, canned, or dried into chipotle; freezes well.",
        "granny_fanny": "Don't be scared of the heat — these pack a punch but are easy to tame in salsa!",
        "companions": ["Basil", "Marigolds", "Carrots"],
        "no_go": ["Fennel"]
    },
    {
        "common_name": "California Wonder Bell Pepper",
        "scientific_name": "Capsicum annuum",
        "cultivar": "California Wonder",
        "type": "Heirloom",
        "growth_habit": "Bushy (2-3 ft tall)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Transplant starters",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Heavy feeder; consistent moisture; support heavy fruits.",
        "days_to_harvest": "75-85 days",
        "harvest_indicators": "Large, blocky, green turning red; thick sweet walls.",
        "yield_family_2": "3-4 plants",
        "yield_family_4": "6-8 plants",
        "preservation": "Fresh eating, roasting, freezing, or canning.",
        "granny_fanny": "The sweetest bell you'll ever grow — perfect for stuffing or snacking straight off the plant!",
        "companions": ["Basil", "Marigolds", "Tomatoes"],
        "no_go": ["Fennel"]
    },
    {
        "common_name": "Thai Hot Pepper",
        "scientific_name": "Capsicum annuum",
        "cultivar": "Thai Hot",
        "type": "Heirloom",
        "growth_habit": "Bushy (compact, 1-2 ft tall)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Transplant starters",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "2 per sq. ft.",
        "care": "Loves heat; water base; very prolific — harvest often.",
        "days_to_harvest": "80-90 days",
        "harvest_indicators": "Tiny bright red fruits on upright clusters; extremely hot.",
        "yield_family_2": "2-3 plants",
        "yield_family_4": "4-6 plants",
        "preservation": "Dried, pickled, or frozen in oil; great for Thai curries.",
        "granny_fanny": "These little firecrackers are hotter than a Nashville summer — use sparingly!",
        "companions": ["Basil", "Marigolds"],
        "no_go": ["Fennel"]
    }
]

# ✅ Paste done! This gives you the first 8 vegetables (mix of heirloom/hybrid, American/Latino/Asian).
# Reply with "next 8 vegetables" when you're ready for vegetables 9-16.
