# vegetable_data.py
# Complete file - 16 vegetables (ready to copy-paste)

vegetables = [
    {
        "common_name": "Cherokee Purple Tomato",
        "scientific_name": "Solanum lycopersicum",
        "cultivar": "Cherokee Purple",
        "type": "Heirloom",
        "growth_habit": "Indeterminate (Vining - needs sturdy trellis)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Bury stems (starters)",
        "spacing_traditional": "24-36 inches",
        "spacing_grid": "1 per sq. ft. (Requires aggressive pruning)",
        "care": "Heavy feeder; sturdy staking; water base (avoid blight).",
        "days_to_harvest": "80-90 days",
        "harvest_indicators": "Deep dusky rose color; slight give.",
        "yield_family_2": "2 plants",
        "yield_family_4": "4-6 plants",
        "preservation": "Best fresh (fresh eating/sauce). Skin too tough for long canning.",
        "granny_fanny": "Don't you dare put these in the fridge! It kills the flavor faster than a late frost.",
        "companions": ["Basil", "Marigolds", "Parsley", "Chives"],
        "no_go": ["Corn", "Potatoes", "Fennel"]
    },
    {
        "common_name": "Brandywine Tomato",
        "scientific_name": "Solanum lycopersicum",
        "cultivar": "Brandywine",
        "type": "Heirloom",
        "growth_habit": "Indeterminate (Vining - needs sturdy trellis)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Bury stems (starters)",
        "spacing_traditional": "24-36 inches",
        "spacing_grid": "1 per sq. ft. (Requires aggressive pruning)",
        "care": "Heavy feeder; sturdy staking; consistent moisture to prevent cracking.",
        "days_to_harvest": "85-100 days",
        "harvest_indicators": "Large pink-red fruits with green shoulders; soft when ripe.",
        "yield_family_2": "2-3 plants",
        "yield_family_4": "5-7 plants",
        "preservation": "Excellent for fresh eating and sauces; can be canned or frozen.",
        "granny_fanny": "This old Pennsylvania Dutch favorite is worth the wait — the flavor is worth its weight in gold!",
        "companions": ["Basil", "Marigolds", "Carrots"],
        "no_go": ["Potatoes", "Fennel", "Corn"]
    },
    {
        "common_name": "Celebrity Tomato",
        "scientific_name": "Solanum lycopersicum",
        "cultivar": "Celebrity",
        "type": "Hybrid",
        "growth_habit": "Determinate (Bush - good for containers)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Bury stems (starters)",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Heavy feeder; stake or cage; disease resistant (VFNT).",
        "days_to_harvest": "70-75 days",
        "harvest_indicators": "Red, round, 8 oz fruits; firm when ripe.",
        "yield_family_2": "3 plants",
        "yield_family_4": "6-8 plants",
        "preservation": "Great for fresh eating, canning, sauces, and drying.",
        "granny_fanny": "This hybrid is a reliable producer even when the weather turns ornery — perfect for busy homesteaders!",
        "companions": ["Basil", "Marigolds"],
        "no_go": ["Potatoes", "Fennel"]
    },
    {
        "common_name": "Better Boy Tomato",
        "scientific_name": "Solanum lycopersicum",
        "cultivar": "Better Boy",
        "type": "Hybrid",
        "growth_habit": "Indeterminate (Vining - needs sturdy trellis)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Bury stems (starters)",
        "spacing_traditional": "24-36 inches",
        "spacing_grid": "1 per sq. ft. (Requires aggressive pruning)",
        "care": "Heavy feeder; sturdy staking; resistant to cracking and disease.",
        "days_to_harvest": "70-75 days",
        "harvest_indicators": "Large red, smooth fruits; firm with slight give.",
        "yield_family_2": "2 plants",
        "yield_family_4": "4-6 plants",
        "preservation": "Excellent for slicing fresh, sauces, and canning.",
        "granny_fanny": "Boy, does this one deliver — big, juicy tomatoes all summer long without the fuss!",
        "companions": ["Basil", "Marigolds", "Onions"],
        "no_go": ["Potatoes", "Corn"]
    },
    {
        "common_name": "Poblano Pepper",
        "scientific_name": "Capsicum annuum",
        "cultivar": "Poblano",
        "type": "Heirloom",
        "growth_habit": "Bushy (2-3 ft tall)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Transplant starters",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Warm soil lover; consistent water; mulch to retain moisture.",
        "days_to_harvest": "75-85 days",
        "harvest_indicators": "Dark green (or red when ripe), 4-6 inch heart-shaped fruits.",
        "yield_family_2": "3-4 plants",
        "yield_family_4": "6-8 plants",
        "preservation": "Best fresh (stuffing/roasting) or dried into ancho chiles; freeze well.",
        "granny_fanny": "These mild Mexican beauties make the best chile rellenos — harvest green for mild heat!",
        "companions": ["Basil", "Marigolds", "Onions"],
        "no_go": ["Fennel", "Kohlrabi"]
    },
    {
        "common_name": "Jalapeño Pepper",
        "scientific_name": "Capsicum annuum",
        "cultivar": "Jalapeño",
        "type": "Heirloom",
        "growth_habit": "Bushy (2-3 ft tall)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Transplant starters",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Full sun; moderate water; pick often to encourage production.",
        "days_to_harvest": "70-80 days",
        "harvest_indicators": "Dark green (or red when ripe), 3-4 inch fruits with slight striping.",
        "yield_family_2": "4 plants",
        "yield_family_4": "8-10 plants",
        "preservation": "Fresh, pickled, canned, or dried into chipotle; freezes well.",
        "granny_fanny": "Don't be scared of the heat — these pack a punch but are easy to tame in salsa!",
        "companions": ["Basil", "Marigolds", "Carrots"],
        "no_go": ["Fennel"]
    },
    {
        "common_name": "California Wonder Bell Pepper",
        "scientific_name": "Capsicum annuum",
        "cultivar": "California Wonder",
        "type": "Heirloom",
        "growth_habit": "Bushy (2-3 ft tall)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Transplant starters",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Heavy feeder; consistent moisture; support heavy fruits.",
        "days_to_harvest": "75-85 days",
        "harvest_indicators": "Large, blocky, green turning red; thick sweet walls.",
        "yield_family_2": "3-4 plants",
        "yield_family_4": "6-8 plants",
        "preservation": "Fresh eating, roasting, freezing, or canning.",
        "granny_fanny": "The sweetest bell you'll ever grow — perfect for stuffing or snacking straight off the plant!",
        "companions": ["Basil", "Marigolds", "Tomatoes"],
        "no_go": ["Fennel"]
    },
    {
        "common_name": "Thai Hot Pepper",
        "scientific_name": "Capsicum annuum",
        "cultivar": "Thai Hot",
        "type": "Heirloom",
        "growth_habit": "Bushy (compact, 1-2 ft tall)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Transplant starters",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "2 per sq. ft.",
        "care": "Loves heat; water base; very prolific — harvest often.",
        "days_to_harvest": "80-90 days",
        "harvest_indicators": "Tiny bright red fruits on upright clusters; extremely hot.",
        "yield_family_2": "2-3 plants",
        "yield_family_4": "4-6 plants",
        "preservation": "Dried, pickled, or frozen in oil; great for Thai curries.",
        "granny_fanny": "These little firecrackers are hotter than a Nashville summer — use sparingly!",
        "companions": ["Basil", "Marigolds"],
        "no_go": ["Fennel"]
    },
    {
        "common_name": "Roma Tomato",
        "scientific_name": "Solanum lycopersicum",
        "cultivar": "Roma",
        "type": "Heirloom",
        "growth_habit": "Determinate (Bush - good for containers)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Bury stems (starters)",
        "spacing_traditional": "18-24 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Heavy feeder; sturdy cage; excellent disease resistance.",
        "days_to_harvest": "75-80 days",
        "harvest_indicators": "Bright red, oval 3-inch fruits; firm with slight give.",
        "yield_family_2": "3 plants",
        "yield_family_4": "6-8 plants",
        "preservation": "Best for canning, sauces, drying, and paste.",
        "granny_fanny": "The classic canning tomato — one of these will fill half your pantry!",
        "companions": ["Basil", "Marigolds", "Carrots"],
        "no_go": ["Potatoes", "Fennel"]
    },
    {
        "common_name": "Danvers Carrot",
        "scientific_name": "Daucus carota",
        "cultivar": "Danvers 126",
        "type": "Heirloom",
        "growth_habit": "Root (6-8 inches tall)",
        "method": "Direct sow",
        "depth": "1/4 inch",
        "spacing_traditional": "2-3 inches (rows 12 inches apart)",
        "spacing_grid": "8-10 per sq. ft.",
        "care": "Loose, deep soil; consistent moisture; thin seedlings early.",
        "days_to_harvest": "65-75 days",
        "harvest_indicators": "Bright orange roots 6-8 inches long; shoulders visible.",
        "yield_family_2": "20-30 plants",
        "yield_family_4": "40-60 plants",
        "preservation": "Fresh, canned, frozen, or stored in root cellar.",
        "granny_fanny": "Sweet, crunchy, and stores all winter — the homestead carrot you want!",
        "companions": ["Onions", "Tomatoes", "Peas"],
        "no_go": ["Dill", "Parsley"]
    },
    {
        "common_name": "Lacinato Kale",
        "scientific_name": "Brassica oleracea",
        "cultivar": "Lacinato",
        "type": "Heirloom",
        "growth_habit": "Upright (24-36 inches)",
        "method": "Starter recommended or direct sow",
        "depth": "1/4 inch",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "2 per sq. ft.",
        "care": "Cool weather; consistent moisture; harvest outer leaves.",
        "days_to_harvest": "60-70 days",
        "harvest_indicators": "Dark blue-green, crinkled leaves; 8-12 inches long.",
        "yield_family_2": "4-6 plants",
        "yield_family_4": "8-12 plants",
        "preservation": "Fresh, sautéed, frozen, or dehydrated.",
        "granny_fanny": "This Italian heirloom is sweeter after frost and keeps producing all winter!",
        "companions": ["Onions", "Beets", "Marigolds"],
        "no_go": ["Strawberries", "Tomatoes"]
    },
    {
        "common_name": "Cherry Belle Radish",
        "scientific_name": "Raphanus sativus",
        "cultivar": "Cherry Belle",
        "type": "Heirloom",
        "growth_habit": "Root (quick 4-6 inches)",
        "method": "Direct sow",
        "depth": "1/2 inch",
        "spacing_traditional": "1-2 inches",
        "spacing_grid": "16 per sq. ft.",
        "care": "Cool weather; succession plant every 2 weeks; keep moist.",
        "days_to_harvest": "25-30 days",
        "harvest_indicators": "Bright red round roots; crisp white flesh.",
        "yield_family_2": "40-60 plants",
        "yield_family_4": "80-100 plants",
        "preservation": "Fresh eating or quick pickles.",
        "granny_fanny": "Fastest crop in the garden — perfect for kids and impatient homesteaders!",
        "companions": ["Carrots", "Peas", "Cucumbers"],
        "no_go": ["Hyssop"]
    },
    {
        "common_name": "Yellow Sweet Spanish Onion",
        "scientific_name": "Allium cepa",
        "cultivar": "Yellow Sweet Spanish",
        "type": "Heirloom",
        "growth_habit": "Bulb (18-24 inches)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / 1 inch (sets)",
        "spacing_traditional": "4-6 inches (rows 12 inches apart)",
        "spacing_grid": "4 per sq. ft.",
        "care": "Full sun; consistent moisture; long-day variety.",
        "days_to_harvest": "110-120 days",
        "harvest_indicators": "Large golden bulbs; tops yellow and fall over.",
        "yield_family_2": "20-30 plants",
        "yield_family_4": "40-60 plants",
        "preservation": "Stores 4-6 months in cool, dry place.",
        "granny_fanny": "Mild, sweet, and huge — these will keep your kitchen stocked all winter!",
        "companions": ["Carrots", "Beets", "Lettuce"],
        "no_go": ["Beans", "Peas"]
    },
    {
        "common_name": "Music Garlic",
        "scientific_name": "Allium sativum",
        "cultivar": "Music",
        "type": "Heirloom",
        "growth_habit": "Bulb (18-24 inches)",
        "method": "Plant cloves in fall",
        "depth": "2-3 inches",
        "spacing_traditional": "6 inches",
        "spacing_grid": "4 per sq. ft.",
        "care": "Fall planting; mulch heavily; harvest when tops brown.",
        "days_to_harvest": "240-270 days (next summer)",
        "harvest_indicators": "Large bulbs with 4-6 big cloves; papery skin.",
        "yield_family_2": "12-16 cloves planted",
        "yield_family_4": "24-32 cloves planted",
        "preservation": "Stores 6-9 months; braid and hang.",
        "granny_fanny": "The best-tasting hardneck garlic — one of the easiest perennials you'll ever grow!",
        "companions": ["Tomatoes", "Beets", "Cabbage"],
        "no_go": ["Peas", "Beans"]
    },
    {
        "common_name": "Clemson Spineless Okra",
        "scientific_name": "Abelmoschus esculentus",
        "cultivar": "Clemson Spineless",
        "type": "Heirloom",
        "growth_habit": "Tall upright (4-6 ft)",
        "method": "Direct sow after soil warms",
        "depth": "1/2 inch",
        "spacing_traditional": "12-18 inches",
        "spacing_grid": "1 per sq. ft.",
        "care": "Full sun; warm soil; harvest every 2 days.",
        "days_to_harvest": "50-60 days",
        "harvest_indicators": "Pods 3-4 inches long, bright green, tender.",
        "yield_family_2": "4-6 plants",
        "yield_family_4": "8-10 plants",
        "preservation": "Fresh, pickled, frozen, or dried.",
        "granny_fanny": "Southern classic that loves Nashville heat — you'll be frying it all summer!",
        "companions": ["Peppers", "Basil", "Marigolds"],
        "no_go": ["Fennel"]
    },
    {
        "common_name": "Tomatillo",
        "scientific_name": "Physalis philadelphica",
        "cultivar": "Mexican",
        "type": "Heirloom",
        "growth_habit": "Bushy (3-4 ft)",
        "method": "Starter recommended",
        "depth": "1/4 inch (seeds) / Transplant starters",
        "spacing_traditional": "24-36 inches",
        "spacing_grid": "1 per 2 sq. ft.",
        "care": "Full sun; cage or stake; needs two plants for pollination.",
        "days_to_harvest": "70-80 days",
        "harvest_indicators": "Papery husk splits; fruit fills husk and feels firm.",
        "yield_family_2": "2-3 plants",
        "yield_family_4": "4-6 plants",
        "preservation": "Fresh salsa verde or canned.",
        "granny_fanny": "The secret to real Mexican salsa — plant at least two or they won't set fruit!",
        "companions": ["Basil", "Marigolds"],
        "no_go": ["Corn", "Potatoes"]
    }
]
